export type FAQItem = {
    question: string;
    answer: string;
};

export const FAQS: FAQItem[] = [
    {
        question: "What insurance products does RevRa support?",
        answer: "RevRa supports all major insurance product types: ACA (Affordable Care Act), Medicare Advantage, Final Expense, Life Insurance, and Group Health. Each has its own pipeline considerations and follow-up cadence tailored by our AI."
    },
    {
        question: "How does AI Lead Scoring work?",
        answer: "Every lead receives a 0-100 score generated by our AI. It considers demographics (age, state, income), insurance factors (coverage type, budget, renewal date), behavioral signals (lead source, engagement), and activity patterns. Scores are color-coded: green (80-100 hot), yellow (50-79 warm), red (0-49 cold), and recalculated automatically after every call or message."
    },
    {
        question: "What is the Emma AI Voice Agent?",
        answer: "Emma AI is our third-party AI voice agent that autonomously calls your leads, holds natural conversations, answers common questions, collects information, and books appointments without human involvement. All results are logged back into RevRa with transcripts, summaries, and next-action recommendations."
    },
    {
        question: "How does lead distribution work?",
        answer: "New leads enter a Lead Pool and are automatically distributed via round-robin to eligible agents. Admins can override manually, assign bulk leads from campaigns, or use bonus leads beyond plan limits. The system respects agent quotas, coverage types, and workspace boundaries."
    },
    {
        question: "What does the Morning Briefing include?",
        answer: "Every morning at 7 AM local time, you receive an AI-generated briefing covering: new leads assigned overnight, overdue follow-ups (red), leads due today (yellow), tomorrow's prep, hot leads (score 85+), appointments, renewals this month, and AI-generated action suggestions. It supports audio playback via Web Speech API for commute listening."
    },
    {
        question: "How does the 14-day free trial work?",
        answer: "New workspaces start with a 14-day free trial, no credit card required. You get full access to all Growth plan features including AI scoring, the dialer, Morning Briefing, and workflow automation. At the end of your trial, choose the plan that fits your agency or cancel with no obligation."
    }
];
